name: Docker Test

on:
  pull_request:
    branches: [ "main", "master" ]

jobs:
  docker-test:
    strategy:
      matrix:
        indexer-version: [0.20.8, 0.20.11, 0.20.12]
    uses: ./.github/workflows/docker_build.yml
    with:
      indexer-version: ${{ matrix.indexer-version }}
      