name: Docker Test

on:
  pull_request:
    branches: [ "main", "master" ]

jobs:
  # get-latest-versions:
  #   uses: ./.github/workflows/fetch_latest_versions.yml

  # docker-test:
  #   needs: get-latest-versions
  #   strategy:
  #     matrix:
  #       indexer-version: ${{ fromJson(needs.get-latest-versions.outputs.versions) }}
  #   uses: ./.github/workflows/docker_build.yml
  #   with:
  #     indexer-version: ${{ matrix.indexer-version }}

  docker-test:
    uses: ./.github/workflows/test_actions.yml
    with:
      indexer-version: v0.20.11