name: Fetch Latest Versions
# This workflow fetches the latest 5 indexer versions from the indexer repo
# and optionally filters all already published versions

on:
  workflow_call:
    inputs:
      autoagora-indexer-service-version:
        description: 'The current autoagora-indexer-service version. If not provided, all versions will be returned.'
        required: false
        type: string
      org-name:
        description: 'The organization name.'
        required: true
        type: string
    outputs:
      versions:
        description: 'Indexer versions to publish'
        value: ${{ jobs.fetch-versions.outputs.tags }}

jobs:
  fetch-versions:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.get-unpublished-tags.outputs.tags }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Fetch unpublished tags
        uses: ./.github/actions/get_unpublished_tags
        id: get-unpublished-tags
        with:
          version: ${{ inputs.autoagora-indexer-service-version }}
          org-name: ${{ inputs.org-name }}
      
      - name: Print the unpublished tags
        run: echo "The unpublished tags are ${{ steps.get-unpublished-tags.outputs.tags }}"