name: Fetch Latest Versions
# This workflow fetches the latest 5 indexer versions from the indexer repo
# and optionally filters all already published versions

on:
  workflow_call:
    inputs:
      autoagora-indexer-service-version:
        description: 'The current autoagora-indexer-service version. If not provided, all versions will be returned.'
        required: false
        type: string
    outputs:
      versions:
        description: 'Indexer versions to publish'
        value: ${{ jobs.fetch-versions.outputs.tags }}

jobs:
  fetch-versions:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.get-unpublished-tags.outputs.tags }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          path: repo

      - name: Checkout the indexer repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: graphprotocol/indexer
          path: indexer

      - name: Fetch unpublished tags
        uses: ./repo/.github/actions/get_unpublished_tags
        id: get-unpublished-tags
        with:
          indexer-repo-path: indexer
          version: ${{ inputs.autoagora-indexer-service-version }}
      
      - name: Print the unpublished tags
        run: echo "The unpublished tags are ${{ steps.get-unpublished-tags.outputs.tags }}"