name: Docker and Semantic Release

on:
  push:
    branches:
      - master

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      contents: write
    outputs:
      published: ${{ steps.release.outputs.published }}
      published_version: ${{ steps.release.outputs.published_version }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Python Semantic Release
        id: release
        uses: tumaysem/python-semantic-release@master
        with:
          additional_options: --github
          github_token: ${{ secrets.GITHUB_TOKEN }}

  docker-release:
    needs: semantic-release
    # if: needs.semantic-release.outputs.published == 'True'
    permissions:
      packages: write
    strategy:
      matrix:
        indexer-version: [0.20.8, 0.20.11, 0.20.12]
    uses: ./.github/workflows/docker_build_release.yml
    with:
      indexer-version: ${{ matrix.indexer-version }}
      # version: ${{ needs.semantic-release.outputs.published_version }}
      version: 0.0.1
      org-name: ${{ vars.ORG_NAME }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}