name: Test

on:
  workflow_call:
    inputs:
      indexer-version:
        description: 'The indexer version to build'
        required: true
        type: string

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Ls files
      - name: List files
        run: ls -la

      - name: Build Docker Image
        uses: redhat-actions/buildah-build@v2
        id: build-image
        with:
          image: autoagora-indexer-service
          platforms: linux/amd64
          build-args: |
            INDEXER_SERVICE_TAG=${{ inputs.indexer-version }}
          containerfiles: |
            ./Dockerfile